# Generated by Django 4.2.1 on 2023-05-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardata',
            name='speed',
        ),
        migrations.AlterField(
            model_name='cardata',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
